version: "3"

services:

  db_deploy:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend_deploy
    volumes:
      - dbdata_deploy:/var/lib/postgresql/data
    restart: unless-stopped

  web_deploy:
    build:
      context: .
      dockerfile: Dockerfile-deploy
    environment:
      - POSTGRES_HOST=db_deploy
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend_deploy
    ports:
      - "8000:8000"
    depends_on:
      - db_deploy
    tty: true
    restart: unless-stopped

networks:
  backend_deploy:

volumes:
  dbdata_deploy: